// Generated by https://quicktype.io

export interface Article {
  id: number;
  createdAt: string;
  title: string;
  category: Category;
  image: string;
  content: string;
  url: string;
}

export enum Category {
  Consejos = "Consejos",
  Productos = "Productos",
  Recetas = "Recetas",
}

export interface Newsletter {
  email: string;
  lastname: string;
  name: string;
  phone: string;
}
